"""Electronic Signature Certificate — the evidentiary page appended to a signed contract.

WHAT THIS IS FOR. When a customer accepts a proposal in the portal they type
their name and tick a consent box. Under ESIGN (15 U.S.C. § 7001) and Kansas's
UETA (K.S.A. 16-1601 et seq.) that is a signature; what decides whether it holds
up is not the glyph but the AUDIT TRAIL — who signed, when, from where, under
exactly which consent wording, and against exactly which document. This module
renders that trail onto one page.

WHY THE DIGESTS ARE THE POINT. "The customer approved the proposal" is worth
little; "the customer approved the PDF whose SHA-256 is
3f2a…" is worth a great deal, because it is falsifiable. Both hashes are
therefore printed WHOLE — 64 hex characters each, never elided — and both are
validated on the way in: a digest that is not 64 hex characters is refused
rather than printed, because a wrong-shaped digest on this page is worse than no
page at all.

HOW IT IS BUILT. Same shape as `invoice_writer`: a pure field-shaping function,
a docx fill against a committed template, and a LibreOffice render. The template
is `templates/Signature_Certificate.docx`, GENERATED by
`prepare_signature_certificate_template.py` from Treadwell's letterhead — read
that module before changing the page.

WHY IT IS A SEPARATE PDF AND NOT A DOCX APPEND. The certificate rides behind the
proposal the customer actually opened, and that proposal must come through
untouched — T&Cs, page breaks, box overrides and all. `docx_merge` says in its
own header why prepending the cover letter is safe and appending after the
proposal body is not (the body-level `w:sectPr` would have to be relocated). So
the join happens at the PDF level in `main.api_admin_signed_contract`, which
copies the proposal's pages object-for-object and never re-renders them. Nothing
here touches Kyle's template XML.

WHAT IT REFUSES, AND WHY LOUDLY. A certificate that is missing a field, or
carries a mis-shaped digest, is not a document to quietly ship with a blank on
it — an estimator who reads "Sent" must be able to trust that what went out is
complete. `field_problems()` names every fault in a sentence the portal can show
a human, and `build_certificate_docx()` raises rather than emitting a document
that still contains a literal `{{token}}` (the same discipline
`main._ensure_value_aliases` enforces on the proposal).
"""
from __future__ import annotations

import io
import re
from typing import Any

from docx import Document
from docx.oxml.ns import qn

TEMPLATE_NAME = "Signature_Certificate.docx"

# Every field the portal sends. Required ones must be present and non-blank;
# the two optional ones are optional because the fact they record can genuinely
# be absent — a signer with no job title, and a contract with no deposit.
REQUIRED_FIELDS = (
    "project_name", "proposal_id", "revision_no",
    "signer_name", "signer_email",
    "signed_at_utc", "signed_at_central",
    "ip_address", "user_agent",
    "options_summary", "total",
    "consent_text", "consent_version",
    "proposal_pdf_sha256", "revision_sha256",
)
OPTIONAL_FIELDS = ("signer_title", "deposit_amount")
FIELDS = REQUIRED_FIELDS + OPTIONAL_FIELDS

# Printed when the signer gave no job title. Not blank: a blank next to a label
# reads as "the field failed to fill", which is the one thing this page must
# never be ambiguous about.
NO_TITLE = "(not provided)"
NO_DEPOSIT = "None"

_HEX64 = re.compile(r"\A[0-9a-fA-F]{64}\Z")
_TOKEN_RE = re.compile(r"\{\{([a-z0-9_]+)\}\}")

# A generous ceiling on the free-text fields. Nothing is ever silently shortened
# — the page takes whatever length it is given and `main` shouts if the render
# runs past one page — but a megabyte of `options_summary` would produce a
# fifty-page certificate, and refusing that by name beats rendering it.
MAX_TEXT = 2000

# Control characters are not legal in XML at all (python-docx will happily write
# them and Word/LibreOffice will then refuse the file). Tabs and newlines inside
# a value would also break the label/value layout, so every one of them becomes
# a space. This is a rendering detail, not a redaction: no character is dropped.
_CONTROL = re.compile(r"[\x00-\x1f\x7f]")


def _clean(v: Any) -> str:
    return _CONTROL.sub(" ", str(v)).strip()


def _money(v: Any) -> str:
    return "${:,.2f}".format(float(v))


def _is_number(v: Any) -> bool:
    if isinstance(v, bool):      # bools are ints in Python; a bool total is a bug
        return False
    if isinstance(v, (int, float)):
        return True
    try:
        float(str(v).replace(",", "").replace("$", "").strip())
        return True
    except (TypeError, ValueError):
        return False


def _number(v: Any) -> float:
    if isinstance(v, (int, float)):
        return float(v)
    return float(str(v).replace(",", "").replace("$", "").strip())


def field_problems(cert: Any) -> list[str]:
    """Every reason this certificate cannot be rendered, each naming its field.

    Returned rather than raised so the caller can answer with ALL of them in one
    400 — the portal is building against this endpoint sight-unseen and a
    one-fault-at-a-time API costs it a round trip per typo. An empty list means
    the fill below cannot leave a blank on the page.
    """
    if not isinstance(cert, dict):
        return ["certificate must be a JSON object"]

    problems: list[str] = []
    for name in REQUIRED_FIELDS:
        v = cert.get(name)
        if v is None or (not isinstance(v, (int, float)) and _clean(v) == ""):
            problems.append("missing required field: " + name)

    for name in ("total", "revision_no"):
        v = cert.get(name)
        if v is None or (not isinstance(v, (int, float)) and _clean(v) == ""):
            continue                                   # already reported missing
        if not _is_number(v):
            problems.append(name + " must be a number, got " + repr(v))

    dep = cert.get("deposit_amount")
    if dep is not None and _clean(dep) != "" and not _is_number(dep):
        problems.append("deposit_amount must be a number or null, got " + repr(dep))

    for name in ("proposal_pdf_sha256", "revision_sha256"):
        v = cert.get(name)
        if v is None or _clean(v) == "":
            continue                                   # already reported missing
        if not _HEX64.match(_clean(v)):
            problems.append(
                name + " must be a 64-character hex SHA-256 digest, got "
                + repr(_clean(v)[:80]))

    for name in FIELDS:
        v = cert.get(name)
        if v is not None and len(_clean(v)) > MAX_TEXT:
            problems.append(
                name + " is longer than " + str(MAX_TEXT) + " characters ("
                + str(len(_clean(v))) + ") — the certificate is one page, not a transcript")

    return problems


def certificate_fields(cert: dict[str, Any]) -> dict[str, str]:
    """Every string that lands on the certificate. Pure — no I/O, no clock.

    Deliberately no timezone maths: `signed_at_central` arrives pre-formatted
    from the portal, which is the one process that knows when the signature was
    taken. Converting here would mean two systems computing the same legal
    timestamp from different clocks, and this box's clock runs ~13 hours off
    Central.
    """
    out = {name: _clean(cert.get(name, "")) for name in
           ("project_name", "proposal_id", "signer_name", "signer_email",
            "signed_at_utc", "signed_at_central", "ip_address", "user_agent",
            "options_summary", "consent_text", "consent_version",
            "proposal_pdf_sha256", "revision_sha256")}

    rev = cert.get("revision_no")
    n = _number(rev)
    out["revision_no"] = str(int(n)) if float(n).is_integer() else str(n)

    out["total"] = _money(_number(cert.get("total")))

    dep = cert.get("deposit_amount")
    out["deposit_amount"] = (NO_DEPOSIT if dep is None or _clean(dep) == ""
                             else _money(_number(dep)))

    out["signer_title"] = _clean(cert.get("signer_title", "")) or NO_TITLE
    return out


# ─── docx plumbing ────────────────────────────────────────────────────
def _fill_paragraph(p_elem, values: dict[str, str], filled: set) -> None:
    """Replace every `{{token}}` in one paragraph, keeping the other runs' formatting.

    Matching happens on the paragraph's CONCATENATED text, not run by run: Word
    splits a value across runs for reasons of its own (spell-check state,
    revision marks), and a template that is re-saved from Word could arrive with
    `{{signer_name}}` sitting in three runs — the trap `invoice_writer` documents.
    The replacement is written into the run that owns the token's first
    character and the rest of the token's characters are dropped, so the bold
    label beside it and the italic quotation marks around it survive untouched.
    """
    ts = list(p_elem.iter(qn("w:t")))
    if not ts:
        return
    texts = [t.text or "" for t in ts]
    full = "".join(texts)
    if "{{" not in full:
        return

    owner: list[int] = []
    for i, s in enumerate(texts):
        owner.extend([i] * len(s))

    pieces: list[list[str]] = [[] for _ in ts]
    pos = 0
    hit = False
    for m in _TOKEN_RE.finditer(full):
        name = m.group(1)
        if name not in values:
            continue                      # unknown token — left alone, caught below
        for c_i in range(pos, m.start()):
            pieces[owner[c_i]].append(full[c_i])
        pieces[owner[m.start()]].append(values[name])
        filled.add(name)
        pos = m.end()
        hit = True
    if not hit:
        return
    for c_i in range(pos, len(full)):
        pieces[owner[c_i]].append(full[c_i])

    for i, t in enumerate(ts):
        t.text = "".join(pieces[i])
        t.set(qn("xml:space"), "preserve")


def _document_text(doc) -> str:
    return "\n".join("".join(t.text or "" for t in p.iter(qn("w:t")))
                     for p in doc.element.body.iter(qn("w:p")))


def build_certificate_docx(cert: dict[str, Any], template_path) -> bytes:
    """Fill the template and return .docx bytes. The template on disk is never
    modified — python-docx loads it and we save to a buffer.

    Raises if the template has drifted away from the field set in either
    direction: a field with nowhere to print is evidence silently lost, and a
    surviving `{{token}}` is a literal placeholder on a legal document.
    """
    values = certificate_fields(cert)
    doc = Document(str(template_path))
    filled: set = set()
    for p_elem in doc.element.body.iter(qn("w:p")):
        _fill_paragraph(p_elem, values, filled)

    unplaced = sorted(set(values) - filled)
    if unplaced:
        raise RuntimeError(
            TEMPLATE_NAME + " has no placeholder for " + ", ".join(unplaced)
            + " — the template and certificate_writer have drifted apart. "
            "Re-run prepare_signature_certificate_template.py.")

    leftover = sorted(set(_TOKEN_RE.findall(_document_text(doc))))
    if leftover:
        raise RuntimeError(
            TEMPLATE_NAME + " still contains the placeholder(s) "
            + ", ".join(leftover) + " after the fill — a customer-facing document "
            "must never show a literal token.")

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def build_certificate_pdf(cert: dict[str, Any], template_path) -> bytes:
    """Fill the template and render it to PDF via LibreOffice (the same renderer
    the proposal and the deposit invoice go through)."""
    import pdf_writer

    return pdf_writer.docx_to_pdf(build_certificate_docx(cert, template_path))
