"""Phase 5 of the v2 estimating program: the model module is js/bid-model.js, and the old name is gone.

The Polish bid maths began as a Polish-only module. It is the saved estimate's model for every work
type now, so Phase 5 gave it the name it keeps, with no change to what it does: the file
`js/polish-bid-core.js` became `js/bid-model.js`, and its browser global `TWPolishBid` became
`TWBidModel`. Every exported name is the same.

WHY A TEST FOR A RENAME. A rename that leaves one reader behind does not fail where the reader was
left. The old file name in a script tag is a 404 and the old global is `undefined`, so the page
script that reads it throws the first time it touches the model, or sits on its loading message for
ever. A rename "finished" by keeping a shim under the old name is the opposite failure: two names for
one thing, which is the defect this whole program exists to remove. So this file holds three things.

  * The new file is there, the old one is not, and no file under frontend/ or backend/ is NAMED for
    the old one (no shim, no stray copy).
  * No file under frontend/ or backend/ still MENTIONS the old file name or the old global, in code,
    in a comment or in a docstring. docs/ is outside this scan on purpose: it is where the history is
    kept. So is this file, which has to say the names in order to look for them.
  * Loaded the way a browser loads it (a script tag, no `require`), the module publishes `TWBidModel`
    and nothing publishes `TWPolishBid`, and every page whose script reads the new global loads the
    module first.

THE SCAN IS TESTED TOO. A search that finds nothing is only worth something if it would have found
something: the self-tests plant a name in each kind of file the repository holds, and plant the things
the scan must leave alone (a binary file, a cache folder, docs/, this file), so a scan that quietly
stopped reading SQL, or started reading a workbook, turns red.

Run under node; a missing node FAILS under CI (tests/_node.py).
"""
from __future__ import annotations

import html.parser
import os
import pathlib

import pytest

from _node import last_json_line, require_node, run_node

TESTS = pathlib.Path(__file__).resolve().parent
ROOT = TESTS.parents[1]
FRONTEND = ROOT / "frontend"
THIS_FILE = pathlib.Path(__file__).resolve()
BOOT_HARNESS = TESTS / "js" / "core-boot-harness.js"

OLD_FILE = "polish-bid-core"
OLD_GLOBAL = "TWPolishBid"
OLD_NAMES = (OLD_FILE, OLD_GLOBAL)
NEW_PATH = "js/bid-model.js"
NEW_GLOBAL = "TWBidModel"

SCANNED = ("frontend", "backend")
# Folders that hold other people's code or generated bytes, never ours.
SKIPPED_DIRS = {"__pycache__", "node_modules", ".pytest_cache", ".git", ".venv", "venv", "site-packages"}


# ── the scan ─────────────────────────────────────────────────────────────────
def scan(root: pathlib.Path, exempt=()):
    """Every mention of an old name under root/frontend and root/backend, and every file named for one.

    Returns (hits, files_read). A hit is (path relative to root, line number, the line); a file whose
    NAME carries an old name is a hit at line 0. Binary files (an image, a font, a workbook, a
    database: they hold a NUL byte) have no source text and are skipped, as is anything that is not
    UTF-8. `exempt` files are not read, but their names still are."""
    hits, files_read = [], 0
    skip = {pathlib.Path(p).resolve() for p in exempt}
    for top in SCANNED:
        base = root / top
        if not base.is_dir():
            continue
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = sorted(d for d in dirnames if d not in SKIPPED_DIRS)
            for filename in sorted(filenames):
                path = pathlib.Path(dirpath) / filename
                rel = path.relative_to(root).as_posix()
                for name in OLD_NAMES:
                    if name in filename:
                        hits.append((rel, 0, "the file name carries " + name))
                if path.resolve() in skip:
                    continue
                raw = path.read_bytes()
                if b"\0" in raw:
                    continue
                try:
                    text = raw.decode("utf-8")
                except UnicodeDecodeError:
                    continue
                files_read += 1
                for number, line in enumerate(text.splitlines(), 1):
                    if any(name in line for name in OLD_NAMES):
                        hits.append((rel, number, line.strip()[:140]))
    return hits, files_read


def _write(root: pathlib.Path, rel: str, content) -> pathlib.Path:
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content if isinstance(content, bytes) else content.encode("utf-8"))
    return path


# ── 1. where the module lives ────────────────────────────────────────────────
def test_the_model_is_at_its_new_path_and_the_old_path_is_empty():
    assert (FRONTEND / NEW_PATH).is_file(), "the model module is not at frontend/" + NEW_PATH
    assert not (FRONTEND / "js" / (OLD_FILE + ".js")).exists(), (
        "a file is still under the old module name: Phase 5 left no shim, so that file is a second "
        "copy of the model")


# ── 2. nothing mentions the old names ────────────────────────────────────────
def test_no_file_under_frontend_or_backend_names_the_old_module_or_global():
    hits, files_read = scan(ROOT, exempt=[THIS_FILE])
    # A floor, not an exact count: about half of today's 504. It only has to prove the walk reached the
    # repository, because a scan that read nothing would report nothing.
    assert files_read >= 250, (
        "the scan read only %d text files: it did not reach the repository, so a clean result means "
        "nothing" % files_read)
    assert not hits, "an old name is back (Phase 5 renamed it to %s / %s):\n%s" % (
        NEW_PATH, NEW_GLOBAL, "\n".join("  %s:%d  %s" % h for h in hits[:40]))


def test_the_scan_sees_a_planted_name_in_each_kind_of_file_and_skips_what_it_must(tmp_path):
    mention = "see js/%s.js and window.%s\n" % (OLD_FILE, OLD_GLOBAL)
    planted = {
        "frontend/js/a.js": "// " + mention,
        "frontend/a.html": '<script src="/js/%s.js"></script>\n' % OLD_FILE,
        "backend/b.py": '"""%s"""\n' % mention,
        "backend/c.sql": "-- " + mention,
        "backend/tests/fixtures/d.json": '{"module": "%s"}\n' % OLD_FILE,
        "backend/tests/js/e.js": "const B = window.%s;\n" % OLD_GLOBAL,
        "backend/tests/test_other.py": "MODULE = 'js/%s.js'\n" % OLD_FILE,
    }
    left_alone = {
        "docs/history.md": mention,                                   # outside frontend/ and backend/
        "backend/__pycache__/f.cpython-311.pyc": b"\0" + mention.encode(),
        "backend/templates/g.xlsx": b"PK\x03\x04\0" + mention.encode(),   # a workbook: binary
        "backend/.venv/lib/h.py": mention,                           # somebody else's code
        "backend/node_modules/i/index.js": mention,
        "backend/tests/test_bid_model_rename.py": mention,           # this file: it has to say the names
        "frontend/img/j.bin": b"\xff\xfe\x00\x00" + mention.encode(),     # not UTF-8, and binary
    }
    for rel, content in {**planted, **left_alone}.items():
        _write(tmp_path, rel, content)
    _write(tmp_path, "frontend/js/%s.js" % OLD_FILE, "// a shim with nothing in it\n")   # named for the old module

    hits, files_read = scan(tmp_path, exempt=[tmp_path / "backend/tests/test_bid_model_rename.py"])

    flagged = {h[0] for h in hits}
    assert flagged == set(planted) | {"frontend/js/%s.js" % OLD_FILE}, sorted(flagged)
    shim = [h for h in hits if h[0] == "frontend/js/%s.js" % OLD_FILE]
    assert shim == [("frontend/js/%s.js" % OLD_FILE, 0, "the file name carries " + OLD_FILE)], (
        "a file kept under the old name must be reported for its NAME even when it says nothing inside")
    by_name = {h[0]: h[2] for h in hits}
    assert OLD_GLOBAL in by_name["backend/tests/js/e.js"] and OLD_FILE in by_name["backend/c.sql"]
    assert files_read == len(planted) + 1, "the scan read the wrong files: %d" % files_read


def test_the_scan_is_clean_on_a_tree_with_only_the_new_names(tmp_path):
    _write(tmp_path, "frontend/js/bid-model.js", "root.%s = api;\n" % NEW_GLOBAL)
    _write(tmp_path, "backend/tests/test_x.py", "MODULE = 'js/bid-model.js'\n")
    assert scan(tmp_path) == ([], 2)


# ── 3. loaded the way a browser loads it ─────────────────────────────────────
def test_loaded_as_a_browser_loads_it_the_module_publishes_the_new_global_and_only_that():
    require_node()
    proc = run_node(BOOT_HARNESS, FRONTEND, NEW_PATH)
    assert proc.returncode == 0, proc.stderr
    out = last_json_line(proc.stdout)
    (script,) = out["scripts"]
    assert script["threw"] is None, "the module did not load as a script tag loads it: %s" % script["threw"]
    assert script["published"] == [NEW_GLOBAL], script["published"]
    assert OLD_GLOBAL not in out["globals"]
    # the real surface, not an empty object under the right name
    assert {"markupChain", "freshModel", "migrateModel", "buildSavePatch", "patchModel", "roundUp",
            "conditionCellWrites"} <= set(script["members"][NEW_GLOBAL])


# ── 4. every page that reads the global loads the module first ───────────────
class _ScriptTags(html.parser.HTMLParser):
    """The `<script src>` tags of a page, in document order. A real parser, not a pattern: a script
    tag inside an HTML comment is not a script tag, and a regular expression cannot tell."""

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.scripts = []          # (src without its query string, runs after parsing)

    def handle_starttag(self, tag, attrs):
        if tag != "script":
            return
        a = dict(attrs)
        if a.get("src"):
            deferred = "defer" in a or a.get("type") == "module"
            self.scripts.append((a["src"].split("?")[0], deferred))


def execution_order(page_html: str):
    """The local script paths of a page in the order a browser RUNS them: scripts without `defer`
    first, in document order, then the deferred ones, in document order."""
    tags = _ScriptTags()
    tags.feed(page_html)
    tags.close()
    return [src for src, deferred in tags.scripts if not deferred] + \
           [src for src, deferred in tags.scripts if deferred]


def readers_of(frontend: pathlib.Path, global_name: str):
    """The URLs of the page scripts that read `window.<global_name>`."""
    needle = "window." + global_name
    return {"/js/" + p.name for p in sorted((frontend / "js").glob("*.js"))
            if needle in p.read_text(encoding="utf-8", errors="replace")}


def pages_that_read_before_the_model_loads(frontend: pathlib.Path):
    """(page, reader) for every page that runs a script reading the global without having run the
    module before it. Also returns how many pages were found to load a reader at all."""
    module_url = "/" + NEW_PATH
    readers = readers_of(frontend, NEW_GLOBAL)
    problems, pages_with_a_reader = [], 0
    for page in sorted(frontend.glob("*.html")):
        order = execution_order(page.read_text(encoding="utf-8"))
        seen_reader = False
        for index, src in enumerate(order):
            if src in readers:
                seen_reader = True
                if module_url not in order[:index]:
                    problems.append((page.name, src))
        pages_with_a_reader += seen_reader
    return problems, pages_with_a_reader


def test_every_page_whose_script_reads_the_new_global_loads_the_model_before_it():
    problems, pages = pages_that_read_before_the_model_loads(FRONTEND)
    assert pages >= 3, "found %d pages loading a script that reads window.%s; library, estimate and intake do" % (
        pages, NEW_GLOBAL)
    assert problems == [], "a page runs a reader of window.%s before /%s has run: %s" % (
        NEW_GLOBAL, NEW_PATH, problems)


def test_the_page_check_goes_red_for_a_missing_a_late_and_a_deferred_model(tmp_path):
    """The check above only means something if it can fail. Each page below is the mistake a rename
    (or the next module someone adds) can make; the good pages must pass beside them."""
    reader = "window.%s" % NEW_GLOBAL
    _write(tmp_path, "js/reader.js", "var B = %s;\n" % reader)
    _write(tmp_path, "js/other.js", "var x = 1;\n")
    model = '<script src="/%s?v=2"></script>\n' % NEW_PATH
    page = '<!DOCTYPE html><html><body>%s</body></html>'
    _write(tmp_path, "good.html", page % (model + '<script src="/js/reader.js"></script>'))
    _write(tmp_path, "missing.html", page % '<script src="/js/reader.js"></script>')
    _write(tmp_path, "late.html", page % ('<script src="/js/reader.js"></script>' + model))
    _write(tmp_path, "deferred.html", page % ('<script defer src="/%s"></script>' % NEW_PATH
                                              + '<script src="/js/reader.js"></script>'))
    _write(tmp_path, "commented-out.html", page % ('<!-- ' + model + ' -->'
                                                   + '<script src="/js/reader.js"></script>'))
    _write(tmp_path, "unrelated.html", page % '<script src="/js/other.js"></script>')

    problems, pages = pages_that_read_before_the_model_loads(tmp_path)

    assert sorted(problems) == [("commented-out.html", "/js/reader.js"), ("deferred.html", "/js/reader.js"),
                                ("late.html", "/js/reader.js"), ("missing.html", "/js/reader.js")]
    assert pages == 5, "good, missing, late, deferred and commented-out each load the reader"
