"""The Handed Off tab: what takes a job off the Active board, and what no longer does.

TWO INSTRUCTIONS, EIGHT DAYS APART, AND THE SECOND ONE REVERSES HALF THE FIRST.

Hanz, 2026-08-20: "I marked Trabon Group project as Won but it's still in the Created but Not Sent
bucket." The fix that day did two things at once — it made the won mark decide a card's position,
and it moved every won job off the Active board onto a Won tab of its own, the way Lost comes off it.

Hanz, 2026-08-28: "Relabel Approved to 'Won/Approved'... the mark as won button would move the
project the Won/Approved not into a separate pipeline... We need to add a button on the Project
container in the Active project named as 'Hand it off'. Then the Won category would be relabeled as
'Handed Off'. After the Handed Off Pipeline would just be one list. Default View should be a list."

The first half of the 2026-08-20 fix stands: a won job no longer sits in the bucket for bids nobody
has sent. The second half is gone, and the reason it had to go is the reason the file it replaced
argued against it before it shipped: A WON JOB STILL HAS WORK ON IT. The deposit is not in, the
contacts are not in, and the sales meeting is run off the Active board — so moving the card the
moment the customer says yes hid live work from the people doing it. The mitigation at the time was
to give the Won tab columns named for what was outstanding, which showed the work but on a screen
nobody was running the meeting from.

WHAT REPLACED IT IS ONE FIELD AND ONE PRESS. Winning is now a COLUMN, `Won/Approved`, in the same
seven-column vocabulary every other card is filed under. What takes a card off the board is
`handed_off` — a human act, stamped by drafts.set_handed_off, derived from nothing. So the two facts
that were fused into one press are separate again: we got it, and operations has it.

THAT SEPARATION IS THE THING WORTH TESTING, because nothing about it is visible in a source read:

  · a won job's column now comes from stage(), not from a second vocabulary, so the routing table
    below is generated by running the real stage() over every distinguishable won shape;
  · isHandedOff reads ONE field and derives nothing, which is what stops a settled job from filing
    itself away before anybody hands it over;
  · handing a job off changes which TAB it is on and must change nothing about which column it would
    draw in, or the tab and the board would disagree about the same card;
  · and Lost still beats both, in every direction.

THE FOUR POOLS PARTITION `ALL`, which is what makes the four pills add up and guarantees no proposal
is reachable from no tab. Precedence: lost, then test, then handed off. A handed-off job that was
then cancelled is Lost only, and a TEST project that was handed off stays under Test, because scratch
work does not become real work by being marked anything.

ONE COLUMN, OPENING AS A LIST. "After the Handed Off Pipeline would just be one list. Default View
should be a list." So the tab has a single column and the view preference became per-tab: Handed Off
opens as a table, the live boards open as boards, and an explicit toggle still sticks for the
session. Which view a tab OPENS in is a three-way precedence and is executed here, not grepped.

EXECUTED, NOT GREPPED. Every claim about a pool, a column, a count or a button runs the real
portal.js function through backend/tests/js/handed-off-tab-harness.js. A source-text assertion let
`ReferenceError: STAGE_CREATED is not defined` take this board down on production on 2026-08-12 with
every test green, and this change swaps a whole column vocabulary inside that same renderer.
"""
import json
import pathlib
import re
import shutil
import subprocess

import pytest

FRONTEND = pathlib.Path(__file__).resolve().parents[2] / "frontend"
HARNESS = pathlib.Path(__file__).resolve().parent / "js" / "handed-off-tab-harness.js"
# The drawer's own harness, borrowed rather than rebuilt. It already renders renderNotSent with the
# thirty-odd names that panel transitively needs bound the way portal.js binds them; a second lift of
# the same function here would be a second thing to keep in step with the page.
DRAWER_HARNESS = pathlib.Path(__file__).resolve().parent / "js" / "drawer-render-harness.js"
CORE = FRONTEND / "js" / "crm-core.js"
PORTAL_JS = FRONTEND / "js" / "portal.js"
PORTAL_HTML_PATH = FRONTEND / "portal.html"
PORTAL_HTML = PORTAL_HTML_PATH.read_text(encoding="utf-8")

HANDOFF_COL = "Handed off"
STAGE_WON = "Won/Approved"

# The live board's seven, in order. "Approved" became "Won/Approved" on 2026-08-28, and the label
# string IS the bucket key in crm-core, so a typo between STAGES and stage() empties a column
# silently rather than throwing — which is why the order is pinned here as well as the membership.
ACTIVE_COLS = ["Created but not sent", "Sent", "Viewed", STAGE_WON, "Deposit submitted",
               "Deposit received", "Contact info"]

needs_node = pytest.mark.skipif(shutil.which("node") is None, reason="node is not installed")


def _code() -> str:
    """portal.js with // comment lines stripped — this file's prose quotes what it asserts."""
    return "\n".join(l for l in PORTAL_JS.read_text(encoding="utf-8").splitlines()
                     if not l.strip().startswith("//"))


# A `_block(fn)` helper that lifted one function's source out of portal.js used to live here, and both
# of its callers have been replaced by renders. It is gone with them rather than left available: it
# read markup out of a template literal through a comment-stripper that only understands `//` lines,
# which made every assertion over it weaker than it looked, and having it in the file is an invitation
# to answer the next behavioural question with a substring search.


@pytest.fixture(scope="module")
def ran():
    if shutil.which("node") is None:
        pytest.skip("node is not installed")
    proc = subprocess.run(
        ["node", str(HARNESS), str(CORE), str(PORTAL_JS), str(PORTAL_HTML_PATH)],
        capture_output=True, text=True, encoding="utf-8", timeout=60)
    assert proc.returncode == 0, proc.stderr
    return json.loads(proc.stdout.strip().splitlines()[-1])


@pytest.fixture(scope="module")
def drawn():
    """The CRM drawer, RENDERED, out of the harness test_drawer_renders.py drives.

    This file needs two of its scenarios: the not-sent drawer before anybody marked the bid, and the
    same drawer after the real Mark won button was pressed and the panel repainted from the patched
    row. That second one is the state Hanz's instruction is about, and it cannot be reached by
    calling a pure function — the drawer has to save, patch and redraw to get there."""
    if shutil.which("node") is None:
        pytest.skip("node is not installed")
    proc = subprocess.run(["node", str(DRAWER_HARNESS), str(FRONTEND)],
                          capture_output=True, text=True, encoding="utf-8", timeout=180)
    assert proc.returncode == 0, (
        "the drawer harness itself failed — read this before assuming a product bug:\n" + proc.stderr)
    return json.loads(proc.stdout.strip().splitlines()[-1])


def _button(html: str, bid: str):
    """The rendered opening <button> tag carrying one id, or None.

    The whole tag, not a boolean, so a caller can see whether the renderer also wrote `disabled` on
    it. A control that is present and dead is the same bug as a missing one, one step further on."""
    m = re.search(r'<button[^>]*\bid="%s"[^>]*>' % re.escape(bid), html)
    return m.group(0) if m else None


def _card(ran, tab: str, pid: str):
    """One rendered card off a rendered board, or None."""
    m = re.search(r'<div class="deal" data-id="%s">.*?\n        </div>' % re.escape(pid),
                  ran["boards"][tab]["html"], re.S)
    return m.group(0) if m else None


# ── the renderer runs at all ─────────────────────────────────────────────────
@needs_node
def test_every_tab_renders_in_both_views_without_throwing(ran):
    """THE 2026-08-12 FAILURE MODE, first because it is the one that takes the page down rather than
    misfiling a card. A new column constant referenced in kanbanHtml but never bound in portal.js is a
    ReferenceError on the first row of a .map(), which paints nothing at all — while the pills above
    the board stay correct, because they are written before board.innerHTML."""
    assert ran["errors"] == {}, "a tab threw instead of rendering: %s" % ran["errors"]


@needs_node
@pytest.mark.parametrize("tab", ["active", "handed_off", "lost", "test"])
def test_every_row_in_the_pool_becomes_a_card(ran, tab):
    """A card silently dropped is the same bug as a card in the wrong column, one step further on."""
    b = ran["boards"][tab]
    assert b["cards"] == len(ran["pools"][tab]), (
        "the %s board drew %s cards for %s rows" % (tab, b["cards"], len(ran["pools"][tab])))
    assert not b["rawToken"], "an unclosed template literal reached the %s board" % tab
    assert not b["undefinedLeak"], "the %s board printed the word undefined at a reader" % tab


# ── the pools ────────────────────────────────────────────────────────────────
@needs_node
def test_the_four_pools_partition_every_proposal(ran):
    """The property the pills depend on: each row in exactly one pool, and every row in one.

    Mutations this kills: filtering handed-off rows off Active without a tab to catch them (the card
    vanishes from the app), and adding the Handed Off pool without taking those rows out of Active
    (the card is in two places and the counts overstate)."""
    seen = [pid for tab in ("active", "handed_off", "lost", "test") for pid in ran["pools"][tab]]
    assert sorted(seen) == sorted(ran["everyId"]), (
        "the tabs do not cover every proposal, so a row is reachable from no tab")
    assert len(seen) == len(set(seen)), "a proposal appears under two tabs, so the counts overstate"


@needs_node
def test_the_project_he_marked_won_is_on_the_active_board_in_the_won_approved_column(ran):
    """BOTH INSTRUCTIONS, IN ONE ASSERTION. `{not_sent: true, won_at: "…"}` — Trabon Group.

    2026-08-20 says it must not be in Created but not sent. 2026-08-28 says it must not have left the
    board to say so. The first fix satisfied one by breaking the other; this is the pair held at once,
    and it is the assertion that fails if anybody restores the old routing."""
    assert "won-unsent" in ran["pools"]["active"], (
        "a project marked won left the Active board without anybody handing it off")
    assert "won-unsent" in ran["boards"]["active"]["by"][STAGE_WON]
    assert "won-unsent" not in ran["boards"]["active"]["by"]["Created but not sent"], (
        "the card he marked won is still in the Created but not sent bucket, which is the whole bug")
    assert "won-unsent" not in ran["pools"]["handed_off"]


@needs_node
def test_an_unmarked_unsent_bid_is_still_in_created_but_not_sent(ran):
    """The control case. Mutation this kills: routing every not-sent row to Won/Approved, which would
    empty the first column of the live board and read as data loss."""
    assert ran["boards"]["active"]["by"]["Created but not sent"] == ["unsent-plain"]


@needs_node
@pytest.mark.parametrize("pid", ["handoff-complete", "handoff-contacts-out", "handoff-unsent"])
def test_only_a_hand_off_takes_a_card_off_the_live_board(ran, pid):
    """The three shapes that reach the tab, and the only thing they have in common is the stamp.

      handoff-complete      everything settled and then handed over — the ordinary path.
      handoff-contacts-out  handed over with the contacts still out, which is reachable because the
                            button warns instead of blocking (see cardActions). It has to land here
                            on the strength of the stamp alone.
      handoff-unsent        never sent, won on the phone, passed straight to operations. Rare, real,
                            and the reason _not_sent_rows carries handed_off_at unconditionally: a
                            synthesised row has no portal field to fall back on."""
    assert pid in ran["pools"]["handed_off"]
    assert pid not in ran["pools"]["active"], "a handed-off job is still on the live board"


@needs_node
@pytest.mark.parametrize("pid", ["won-test", "handoff-test"])
def test_a_test_project_stays_under_test_however_it_was_marked(ran, pid):
    """Scratch work does not become real work by being marked won or handed off, and Test is the one
    tab its owner looks under. Mutation this kills: testing isHandedOff before isTest in boardPool."""
    assert pid in ran["pools"]["test"]
    assert pid not in ran["pools"]["handed_off"], (
        "somebody's test project is being counted as work we handed to operations")


@needs_node
@pytest.mark.parametrize("pid", ["lost-after-won", "lost-after-marked-won", "lost-after-handoff"])
def test_a_job_cancelled_after_the_fact_appears_only_under_lost(ran, pid):
    """Both routes to won and the route past it, cancelled afterwards. isLost keeps precedence —
    boardPool asks it first, before the test flag and before the hand-off — because a sent project's
    closed_lost lives in the portal where the by-hand marks cannot see or clear it.

    `lost-after-handoff` is the new one: a job operations already had, then cancelled. It is the row
    that proves the new predicate did not jump the queue in front of Lost."""
    assert pid in ran["pools"]["lost"]
    for tab in ("active", "handed_off", "test"):
        assert pid not in ran["pools"][tab], "a cancelled job is on the %s tab as well as Lost" % tab


@needs_node
def test_an_approved_job_with_the_money_still_out_is_won_approved_but_not_won(ran):
    """THE distinction isWon's derived half exists for, and the column is deliberately WIDER than it.

    The column says "the customer said yes". The button says "we may hand this over". Approval alone
    earns the first and not the second: this is the most worth-chasing row there is, so it belongs in
    front of the meeting under Won/Approved, and it must not be offered a hand-off while the deposit
    it was invoiced for has not arrived."""
    assert "approved-unpaid" in ran["boards"]["active"]["by"][STAGE_WON]
    assert ran["stageRouting"]["approved + deposit requested"] == STAGE_WON
    assert ran["routingIsWon"]["approved + deposit requested"] is False, (
        "an approved job with the money still out is being called won, which would offer a hand-off "
        "on a job nobody has been paid for")


# ── the columns, all seven of them, on the one board there is ────────────────
@needs_node
def test_the_active_board_draws_the_seven_columns_in_order(ran):
    """Built from crm-core's STAGES rather than typed out again, and asserted in order. The rename
    lands here: "Approved" is the string that changed, and it is a bucket KEY, so a stage() that kept
    returning the old spelling would empty this column in silence rather than throwing."""
    assert ran["boards"]["active"]["cols"] == ACTIVE_COLS
    assert ran["stages"] == ACTIVE_COLS, "STAGES and the rendered board disagree"
    assert ran["stageWon"] == STAGE_WON


@needs_node
@pytest.mark.parametrize("col", ACTIVE_COLS)
def test_no_active_column_is_unreachable(ran, col):
    """Every one of the seven has a card in it, RENDERED. A column no card can reach is a column that
    should be removed, so this is the evidence for that decision — and it is worth keeping now that
    won jobs are back, because the answer changed: two of these were reachable only through a revised
    proposal while won jobs lived elsewhere, and they carry ordinary won work again."""
    assert ran["boards"]["active"]["by"][col], (
        "no card can reach the %s column any more, so the live board carries a heading that can "
        "only ever be empty" % col)


@needs_node
def test_every_won_shape_routes_into_the_live_columns_the_way_the_names_claim(ran):
    """THE ROUTING TABLE, GENERATED by running the real stage() over every distinguishable state a
    won job can be in — so the table anybody reasons from is executed rather than argued.

    This is where the reversal is actually visible. Until 2026-08-28 these shapes were answered by a
    second vocabulary only the Won tab spoke ("Won before approval", "Deposit outstanding"); now they
    are answered by the same seven columns every other card is filed under, which is the entire point.

    The two rows that pin it down:

      not_sent + won_at   Won/Approved, NOT Created but not sent. The reported bug, and the half of
                          the 2026-08-20 fix that stands.
      deposit received    Deposit received, NOT Won/Approved. The won mark does not outrank work that
                          is genuinely further along, so nothing downstream gets hidden by a phone
                          call — which is the objection the Won tab was invented to answer and this
                          ordering answers without moving the card."""
    assert ran["stageRouting"] == {
        "not_sent + won_at": STAGE_WON,
        "sent + won_at": STAGE_WON,
        "sent + won_at + deposit_required false": STAGE_WON,
        "viewed + won_at": STAGE_WON,
        "approved + deposit requested": STAGE_WON,
        "approved + deposit_required false": STAGE_WON,
        "deposit submitted": "Deposit submitted",
        "deposit received + contacts missing": "Deposit received",
        "everything settled": "Contact info",
        "not_sent, unmarked": "Created but not sent",
        "sent, unmarked": "Sent",
        "viewed, unmarked": "Viewed",
    }


@needs_node
def test_a_won_job_whose_deposit_has_landed_still_reads_as_deposit_received(ran):
    """THE MITIGATION, and it is now free rather than bought with a second screen.

    The old design's whole difficulty was that moving a won card hid the deposit and contacts chasing.
    Keeping the card and ordering the money checks ABOVE the won mark means the column always names
    the work that is actually left, on the board the meeting is run from."""
    assert "won-contacts-out" in ran["boards"]["active"]["by"]["Deposit received"]
    assert "won-complete" in ran["boards"]["active"]["by"]["Contact info"]
    assert "won-deposit-out" in ran["boards"]["active"]["by"][STAGE_WON], (
        "a won job whose deposit has NOT landed is being filed under a column that says it has")


@needs_node
def test_handing_a_job_off_does_not_change_which_column_it_would_draw_in(ran):
    """Two separate facts, and the routing must keep them separate.

    The Handed Off tab is one flat list, so this is invisible there — until somebody presses Bring it
    back, at which point the card returns to whichever Active column its own dates earn. If the stamp
    quietly re-columned the card, the destination the drawer promises and the column it lands in would
    be different things, and the reversal would be lossy."""
    assert ran["stageRoutingHandedOff"] == ran["stageRouting"], (
        "the hand-off stamp is changing a card's column, so handing a job off and bringing it back "
        "would not return it to where it was")


@needs_node
def test_the_hand_off_mark_is_read_and_never_derived(ran):
    """The one field, and NO second half. isWon has a derived half on purpose — approved with the
    deposit settled counts, because those facts are recorded elsewhere and re-typing them would be
    busywork. Handing over is the opposite: there is no timestamp anywhere in either database that
    means "operations has it", so deriving one would file a settled job away before anybody had it,
    which is precisely the failure the 2026-08-20 design shipped."""
    assert ran["handoffPredicate"] == {
        "stamped": True,
        "everything settled, unstamped": False,
        "won by hand, unstamped": False,
        "empty": False,
        "null": False,
    }


# ── one flat list ────────────────────────────────────────────────────────────
@needs_node
def test_the_handed_off_tab_is_one_flat_list(ran):
    """Hanz: "After the Handed Off Pipeline would just be one list." Four outstanding-work columns
    made sense while the tab was where won jobs went to be chased; nothing is outstanding on a job
    operations has, so columns would be four headings answering a question nobody is asking."""
    assert ran["boards"]["handed_off"]["cols"] == [HANDOFF_COL]
    assert ran["handoffCols"] == [HANDOFF_COL], "the column list is not crm-core's own"


@needs_node
def test_no_card_is_counted_twice_on_the_handed_off_tab(ran):
    flat = [pid for col in ran["boards"]["handed_off"]["by"].values() for pid in col]
    assert sorted(flat) == sorted(ran["pools"]["handed_off"])
    assert len(flat) == len(set(flat))


@needs_node
def test_the_handed_off_tab_cannot_start_a_new_proposal(ran):
    """+ New files a brand-new bid into the column it sits on. Executed rather than grepped — the gate
    is an expression whose presence in the source says nothing about which tabs it lets through."""
    assert ran["boards"]["handed_off"]["newButton"] is False, (
        "the + New button renders on the Handed Off tab, which would file a new bid as already "
        "handed to operations")
    assert ran["boards"]["lost"]["newButton"] is False
    for tab in ("active", "test"):
        assert ran["boards"][tab]["newButton"] is True, "the %s tab lost its + New button" % tab


@needs_node
def test_an_empty_handed_off_tab_says_which_kind_of_empty_it_is(ran):
    """One empty column reads worse than four did — a lone heading over nothing looks like a board
    that failed to load. And the two kinds of empty need different answers: "nothing handed off yet"
    is news, "nothing matches those filters" means clear the filter.

    BOTH BRANCHES RENDERED. The filtered case needs the pool and the drawn list to DISAGREE, which is
    what visible() does on the real page, so the harness renders that separately."""
    unfiltered = ran["emptyHandoff"]
    assert "Nothing handed off" in unfiltered
    assert "yet" in unfiltered, "an untouched Handed Off tab reads as a filter problem"
    assert "filter" not in unfiltered, (
        "an unfiltered empty tab is telling the reader to clear a filter they have not set")
    assert "Hand it off" in unfiltered, (
        "the empty tab does not say what puts a job here, which is the one thing a reader who has "
        "never seen it populated needs")
    assert 'class="col' not in unfiltered, (
        "an empty Handed Off tab still draws its column heading, which reads as a broken page")

    filtered = ran["emptyHandoffFiltered"]
    assert filtered["pool"] and not filtered["shown"], (
        "the filtered scenario is not filtered: %s in the pool, %s drawn"
        % (filtered["pool"], filtered["shown"]))
    assert "Nothing handed off matches those filters." in filtered["html"], (
        "a tab emptied by the toolbar says nothing has been handed off, so the reader clears nothing "
        "and concludes the board is broken: %s" % filtered["html"])
    assert 'class="col' not in filtered["html"]


@needs_node
def test_the_handed_off_tab_opens_as_a_list_and_the_live_boards_do_not(ran):
    """Hanz: "Default View should be a list."

    EXECUTED through the real readView with a real store behind it. The default is a claim about the
    FIRST time a rep opens the tab — the state every rep is in until they toggle it — and a source
    read of the ternary cannot tell you which branch a real stored value takes."""
    fresh = {tab: ran["views"][tab]["fresh"] for tab in ran["pills"]}
    assert fresh["handed_off"] == "table", "the Handed Off tab does not open as a list"
    for tab in ("active", "lost", "test"):
        assert fresh[tab] == "board", (
            "the %s tab stopped opening as a board, so the list default leaked past the one tab it "
            "was asked for" % tab)


@needs_node
@pytest.mark.parametrize("tab", ["active", "handed_off", "lost", "test"])
def test_an_explicit_view_choice_beats_the_default_on_every_tab(ran, tab):
    """The toggle still sticks for the session, per tab, in both directions — including the one that
    means "give me the board on the tab that defaults to a list". A default implemented by ignoring
    the stored value would pass the test above and take the toggle away.

    Junk falls back to the tab's default rather than to a fixed view: a stored value from before the
    key was per-tab, or from a hand-edited session, must not leave the Handed Off tab on a board."""
    v = ran["views"][tab]
    assert v["storedTable"] == "table"
    assert v["storedBoard"] == "board", "an explicit board choice is being overridden on %s" % tab
    assert v["storedJunk"] == v["fresh"], (
        "an unrecognised stored view on %s falls back to something other than that tab's default"
        % tab)


# ── the card still carries its facts, and its buttons ────────────────────────
@needs_node
def test_a_won_unsent_card_still_shows_its_money_and_its_estimator(ran):
    """A card whose column moved must not lose what makes it worth reading. The money comes from
    `bid_total` on a synthesised row (cardTotal reads both fields, and calling an unsent draft's
    working figure "approved" would put a word on it nobody has earned), and the estimator falls back
    to whoever priced it, drawn with a "?" because nobody chose them."""
    body = _card(ran, "active", "won-unsent")
    assert body, "the card he marked won did not render on the live board"
    assert "$88,000.00" in body, "the bid value is gone from the card: %s" % body
    assert "Kyle" in body, "the estimator is gone from the card"
    assert "chip-won" in body, "nothing on the card says it has been won"


@needs_node
def test_a_handed_off_card_says_so_on_its_face(ran):
    """The tab is one flat list, so the chip is the only thing on the card that dates the hand-off."""
    body = _card(ran, "handed_off", "handoff-complete")
    assert body, "a handed-off card did not render"
    assert "chip-handoff" in body, (
        "a card on the Handed Off tab carries nothing saying when it was handed over")


@needs_node
def test_a_won_card_offers_the_hand_off_and_an_unmarked_one_offers_the_mark(ran):
    """Hanz: "We need to add a button on the Project container in the Active project named as 'Hand
    it off'." RENDERED off the live board, because which button a card gets is two predicates
    interacting and the source shows only the ternary.

    Both labels are his: "Mark as won/approved", and the column it names."""
    won = _card(ran, "active", "won-unsent")
    assert 'data-handoff="won-unsent"' in won, "a won card offers no Hand it off"
    assert "Hand it off" in won
    assert 'data-won="won-unsent"' not in won, "it offers to mark a project it has already marked"

    plain = _card(ran, "active", "unsent-plain")
    assert 'data-won="unsent-plain"' in plain, "an unwon card offers no way to mark it"
    assert "Mark as won/approved" in plain, "the card's button kept the old label"
    assert 'data-handoff="unsent-plain"' not in plain, (
        "a card nobody has won offers to hand it to operations")

    for pid in ("won-unsent", "unsent-plain"):
        assert 'data-lost="%s"' % pid in _card(ran, "active", pid), (
            "%s cannot be closed lost from its card, so a job that dies after a verbal yes has to "
            "be un-won first" % pid)


@needs_node
def test_an_approved_but_unpaid_card_is_not_offered_the_hand_off(ran):
    """The gate is isWon, which is wider than the column. Offering a hand-off here would let a job
    leave the board with an invoice outstanding and nobody chasing it."""
    body = _card(ran, "active", "approved-unpaid")
    assert 'data-handoff=' not in body, (
        "a job whose deposit has not arrived is being offered to operations: %s" % body)
    assert 'data-won="approved-unpaid"' in body


@needs_node
def test_a_handed_off_card_offers_nothing(ran):
    """Decided. The way back is the drawer's bring-back, which needs a prompt naming the destination
    and so cannot live on a 224px card."""
    body = _card(ran, "handed_off", "handoff-complete")
    assert "deal-acts" not in body, "a handed-off card still offers board buttons: %s" % body


@needs_node
def test_the_handed_off_tab_reads_as_pressed_and_the_four_counts_add_up(ran):
    """syncTabs computes its numbers inline rather than through boardPool (which closes over TAB), so
    the precedence is spelled out twice and this is what catches the two copies drifting. A pill
    advertising 3 and then showing 2 is worse than no number at all."""
    counts = ran["counts"]
    assert set(counts) == set(ran["pills"]), (
        "syncTabs and the markup disagree about which pills exist: %s vs %s"
        % (sorted(counts), sorted(ran["pills"])))
    assert sum(counts.values()) == len(ran["everyId"]), (
        "the four pill counts sum to %s, not the %s proposals there are"
        % (sum(counts.values()), len(ran["everyId"])))
    for tab in ran["pills"]:
        assert counts[tab] == len(ran["pools"][tab]), (
            "the %s pill says %s and the board shows %s" % (tab, counts[tab], len(ran["pools"][tab])))
    assert ran["pressed"]["handed_off"] == "true", (
        "the Handed Off pill does not read as selected on the Handed Off tab")


# ── the drawer: mark won, hand off, and both ways back ───────────────────────
# Hanz, 2026-08-20: "Even for created not sent we must be able to mark it as won or lost."
#
# BOTH CONTROLS ALREADY WORKED: portal.js renderNotSent renders the Won control and the Mark closed
# lost button into the Follow-up panel of every not-sent drawer, wireWon and wireNotSentLost bind
# them, and both post to /api/draft/<id>/status.
#
# What the 2026-08-28 change adds is a THIRD outcome in the same panel, and the panel now has five
# distinguishable states rather than three. They are rendered one by one below, because the
# difference between "no control because there is nothing to do" and "no control because the render
# failed" is invisible to a reader and to a source check alike.
@needs_node
@pytest.mark.parametrize("pid", ["won-unsent", "won-marked-sent", "won-deposit-out"])
def test_the_drawer_offers_the_hand_off_and_the_undo_on_a_bid_somebody_marked_won(ran, pid):
    """RENDERED, from the real wonControlHtml. `if (false) …won-undo…` leaves the id in the function
    and keeps a source check green while offering nothing.

    THREE shapes, and the third is the one the reversal added: never sent, sent-but-unapproved, and
    approved with the deposit still out. The undo has to be there for all of them — the middle one is
    the mark most likely to be wrong, because it is the one somebody made off a phone call — and so
    does the hand-off, because a job can be passed to operations before the money lands."""
    html = ran["wonControl"][pid]
    assert 'id="handoff-mark"' in html, "a won bid offers no way to hand it to operations"
    assert 'id="won-undo"' in html, "a bid marked won offers no way back"
    assert 'id="won-mark"' not in html, "it offers to mark a project it has already marked"
    assert "Won/Approved column" in html, (
        "the panel does not say which column the card is in, which is exactly what he could not find")
    assert "Handed Off tab" in html, "it does not say where Hand it off would send the card"


@needs_node
def test_the_drawer_offers_the_mark_on_an_unsent_bid_nobody_has_marked(ran):
    """And it says the card STAYS, which is the sentence the whole reversal is about: the old copy
    promised the opposite, and a rep who read it would not press the button before the deposit was in."""
    html = ran["wonControl"]["unsent-plain"]
    assert 'id="won-mark"' in html, "an unsent bid cannot be marked won from its drawer"
    assert 'id="won-undo"' not in html
    assert 'id="handoff-mark"' not in html, (
        "a bid nobody has won offers to hand it to operations")
    assert "Mark as won/approved" in html, "the drawer's button kept the old label"
    assert "STAYS on the Active board" in html, (
        "the panel does not say the card stays, so a rep still reads Mark won as 'file it away'")


@needs_node
def test_a_job_won_by_the_numbers_has_no_undo_but_can_still_be_handed_off(ran):
    """THE ONE STATE WITH NOTHING TO BRING BACK: approved, deposit in, contacts in, and NOBODY marked
    it won — the numbers did. There is no mark to clear, so an Undo here would save and change
    nothing, which reads as a broken control.

    It still gets the hand-off, and that is the point of the reversal: this is exactly the job the old
    design filed away by itself the moment the last number landed. Now somebody has to say so."""
    html = ran["wonControl"]["won-complete"]
    assert html, "the derived-won panel renders nothing at all"
    assert 'id="won-undo"' not in html, (
        "it offers to take off a mark nobody made, which would change nothing visible")
    assert 'id="won-mark"' not in html, "it offers to mark a job that already counts as won"
    assert 'id="handoff-mark"' in html, (
        "a job with nothing outstanding cannot be handed over, so it sits on the live board forever")
    assert "nothing to bring back" in html, (
        "the panel is silent about why it has no undo: %r" % html)
    assert "Proposal tab" in html, (
        "it does not say where un-approving it or unwinding the deposit actually live")


@needs_node
@pytest.mark.parametrize("pid", ["handoff-complete", "handoff-unsent"])
def test_a_handed_off_job_is_offered_the_bring_back_and_nothing_else(ran, pid):
    """The state past the win. Hand it off again is a button that does nothing, and so is the won
    undo — un-winning a job operations already has would leave it on a tab its own predicate no
    longer explains. One control, and it names where the card goes."""
    html = ran["wonControl"][pid]
    assert 'id="handoff-undo"' in html, "a handed-off job cannot be brought back"
    assert 'id="handoff-mark"' not in html, "it offers to hand off a job already handed off"
    assert 'id="won-undo"' not in html, (
        "it offers to un-win a job operations has, which would strand it on the Handed Off tab")
    assert "Handed Off tab" in html
    assert "Bring it back" in html


@needs_node
def test_a_closed_lost_bid_is_offered_neither(ran):
    """Lost beats everything, so a Mark won or a Hand it off here would save and change nothing
    visible, which reads as a broken control. Reactivate beside it is the way back."""
    assert ran["wonControl"]["lost-after-won"] == ""


@needs_node
def test_both_outcome_controls_survive_marking_an_unsent_bid_won(drawn):
    """Hanz, 2026-08-20: "Even for created not sent we must be able to mark it as won or lost."

    RENDERED, on both sides of the mark. What matters is not which identifier appears in the
    function; it is that a rep looking at a bid nobody has sent is offered both outcomes, before and
    after somebody records one of them.

    The "after" state is the drawer the real Mark won button repainted from the row it patched. It
    was load-bearing when the card MOVED tab; it stays load-bearing now that it does not, because a
    won unsent bid the GC then cancels still has to be closeable without being un-won first."""
    assert not drawn["errors"], "the drawer threw instead of rendering: %s" % drawn["errors"]
    before = drawn["won"]["notSentOffered"]["html"]
    after = drawn["won"]["notSentMarked"]
    assert after["rowWonAt"], (
        "the mark never saved, so the 'after' panel is not the won state and this test proves "
        "nothing about it")

    for label, html, won_id in (("before the mark", before, "won-mark"),
                                ("after the mark", after["html"], "won-undo")):
        lost = _button(html, "ns-lost")
        won = _button(html, won_id)
        assert lost, "%s: the not-sent drawer offers no Mark closed lost" % label
        assert won, "%s: the not-sent drawer offers no %s control" % (label, won_id)
        assert "disabled" not in lost, "%s: Mark closed lost renders dead: %s" % (label, lost)
        assert "disabled" not in won, "%s: the won control renders dead: %s" % (label, won)
    # And the two are genuinely different states, or the loop above passed twice on one panel.
    assert _button(before, "won-undo") is None
    assert _button(after["html"], "won-mark") is None
    # The third outcome appears with the win and not before it, in the real drawer rather than in
    # wonControlHtml called directly — which is the only place the panel's own gating is exercised.
    assert _button(before, "handoff-mark") is None, (
        "a bid nobody has won is offered a hand-off in the live drawer")
    assert _button(after["html"], "handoff-mark"), (
        "marking an unsent bid won does not surface Hand it off, so the card can never leave the "
        "board without a second visit")


# ── the things a source read is the right tool for ───────────────────────────
def test_the_tab_is_one_named_set_and_the_markup_has_a_pill_for_each():
    """TAB is validated against TABS on load, so a tab missing from that list cannot be restored from
    a stored session, and a pill missing from the markup cannot be clicked."""
    code = _code()
    m = re.search(r"const TABS = \[([^\]]*)\]", code)
    assert m, "the tab list is not one named set, so the stored value and the markup can drift"
    tabs = re.findall(r'"([a-z_]+)"', m.group(1))
    assert "handed_off" in tabs, (
        "handed_off is not in TABS, so a stored Handed Off tab falls back to Active")
    assert "won" not in tabs, "the retired Won tab is still restorable from a stored session"
    for t in tabs:
        assert 'data-tab="%s"' % t in PORTAL_HTML, "the %s tab has no pill in the markup" % t


def test_the_hand_off_rule_lives_in_crm_core_and_the_won_columns_are_gone():
    """One definition, in the module with no DOM that node exercises, and the retired one actually
    removed rather than left to rot.

    A dead wonColumn kept in the file is worse than a stale comment: it still compiles, it still
    exports, and the next person to want "which column does a won job get" would find two answers
    and no way to tell which one the board uses."""
    core = CORE.read_text(encoding="utf-8")
    assert "function isHandedOff" in core and "isHandedOff: isHandedOff" in core, (
        "isHandedOff is not defined and exported by crm-core")
    assert "function wonColumn" not in core and "function groupWon" not in core, (
        "the retired Won-tab grouping is still in crm-core, so there are two answers to which "
        "column a won job gets")
    assert "WON_COLS" not in core, "the retired Won-tab column list is still exported"
    assert 'var STAGE_WON = "%s"' % STAGE_WON in core, (
        "the Won/Approved label is not a named constant, so STAGES and stage() can spell it "
        "differently and empty the column in silence")

    js = PORTAL_JS.read_text(encoding="utf-8")
    assert "function isHandedOff" not in js, (
        "portal.js has grown its own copy of the hand-off predicate")


# There is deliberately NO test here pinning the chipsHtml note that records the 2026-08-19 reversal.
# One existed and asserted that "2026-08-20" and the word "REVERSE" appeared in that comment, which
# could only ever fail if somebody edited prose: it caught no code change at all and reported coverage
# of a decision nobody had tested. The comment is worth keeping and is still there; pretending it was
# covered is what had to go.
